Jy/XButton, Input, Search Filter 구현
boostcamp-2020/IssueTracker-06 pull request #97
Opened 2020-11-04 11:05 UTC by 16010948

- XButton 구현
  - 필터를 초기화하는 버튼 구현
- Input 구현
 - Search Filter 구현
  - 검색 필터 구현

#66 #82 #69

2020-11-04 11:29 UTC, cyjo9603 reviewed
전체적으로 잘 작성하신 것 같습니다.

2020-11-04 11:29 UTC, cyjo9603 commented on client/src/themes/index.ts
> +    SECONDARY: '#586069',
이런 미세한 오타를 발견해주시다니 👍👍👍

2020-11-04 11:29 UTC, cyjo9603 commented on client/src/components/molecules/XButton/XButton.tsx
> +  cursor: pointer;
속성끼리는 붙이고 & > 같은 다른 스타일 적용할 때만 띄워주면 좋을 것 같아요

2020-11-04 11:29 UTC, cyjo9603 commented on client/src/components/molecules/SearchFilter/SearchFilter.tsx
> +const StyledButton = styled.button``;
비어있는 컴포넌트라면 굳이 styled를 사용할 필요 없이 `<ul></ul>`처럼 직접 태그를 사용해도 됩니다

2020-11-04 11:29 UTC, cyjo9603 commented on client/src/components/atoms/icons/Dropdown.tsx
> +    </svg>
svg에 필요없는 속성(x, y, className 등)은 제거하고 넣는게 더 조아용😊😊

2020-11-04 11:29 UTC, cyjo9603 commented on client/src/components/atoms/icons/Reset.tsx
> +    </svg>
여기도 마찬가지로 svg에 필요없는 속성은 빼주는게 죠습니다.
실제로 속성 하나씩 빼보면서 필요한 속성이 뭔지 눈으로 확인해 보는 것도 좋을 것 같아요 :)

2020-11-04 11:29 UTC, cyjo9603 commented on client/src/components/atoms/Input/Input.tsx
> +  placeholder,
선택전 인자로 넣어준 값에는 기본값을 설정해 주는 것이 좋아용 😊

2020-11-04 11:46 UTC, Eunbin-Kim requested changes
onClick 함수, map 활용 등 사용하지 않았던 부분을 구현해주어서 리뷰하며 많이 배워갑니다~!

2020-11-04 11:46 UTC, Eunbin-Kim commented on client/src/components/molecules/XButton/XButton.stories.tsx
> +  };
나중을 위해서 onclick에 어떤 메소드가 들어갈지 적어준 부분 너무 좋아요~!

2020-11-04 11:46 UTC, Eunbin-Kim commented on client/src/components/molecules/XButton/XButton.tsx
> +  onClick: (e: React.MouseEvent<HTMLButtonElement>) => void;
onclick에서는 event 객체를 활용할 일이 없을 것으로 생각됩니다!
event 객체를 넣어주면 이 컴포넌트를 사용할 때 항상 저 event 객체를 넣어주어야 해서 타입 오류가 잦게 날 수 있을 것 같습니다.

2020-11-04 11:46 UTC, Eunbin-Kim commented on client/src/components/molecules/SearchFilter/SearchFilter.tsx
> +      <StyledSummary>
summary tag 새롭게 배워갑니다~!

2020-11-05 01:46 UTC, cyjo9603 approved these changes

2020-11-05 01:46 UTC, cyjo9603 commented on client/src/components/molecules/FilterModal/FilterModal.tsx
> +  display: string;
display type을 string보다는 좀더 명확하게 (ex 'flex' | 'block') 하는게 좋습니당

2020-11-05 01:57 UTC, Eunbin-Kim approved these changes

2020-11-05 01:59 UTC, merged